### ISSUE TITLE
[1.12.2] Snad-1.12.1-1.7.09.16a works, but is not marked as such on Curse

### ISSUE THREAD

**Issue by sandalle** [TheRoBrit/Snad#10]
[Snad-1.12.1-1.7.09.16a](https://minecraft.curseforge.com/projects/snad/files/2480458) works on MC 1.12.2 (Forge Mod Loader 14.23.0.2515), but is not marked as such on Curse disallowing modpacks from using it.

**Comment by RoBrit** [comment]
I've added 1.12.2 to the list of available versions. Thanks for testing with 1.12.2 and confirming that it works with that version. 

Closing issue as it should now be resolved.

**Comment by sandalle** [comment]
Thank you for the quick turnaround @TheRoBrit ! :)
