### ISSUE TITLE
[1.21] Neoforge craash with snad

### ISSUE THREAD

**Issue by Periam** [TheRoBrit/Snad#27]
Latest neoforge version crash with Snad mod installed.

Neoforge 21.0.98
jei-1.21-neoforge-19.5.0.35.jar
Snad-21.0.0.jar

[Uploading crash-2024-07-17_08.40.53-fml.txt…]()

![Screenshot 2024-07-16 200238](https://github.com/user-attachments/assets/420147ef-8418-466f-9cfe-c0ec321b97a7)

**Comment by MokahTGS** [comment]
Adding onto this with Neoforge 21.0.112

Crashlog: https://pastebin.com/6Ux3Z2mP

**Comment by MichaelHillcox** [comment]
Fixed as of 21.0.2 

Should be on CF soon
