### ISSUE TITLE
[Suggestion] Any plans to add a mod to Modrinth?

### ISSUE THREAD

**Issue by Alter73** [TheRoBrit/Snad#28]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if Snad mod was also in Modrinth, otherwise I have to download it separately for each modpack and check for its updates, but this is very inconvenient when creating modpacks.

**Comment by RoBrit** [comment]
I've now added the mod to Modrinth and will do my best to include future releases on both CurseForge and Modrinth as platforms
